### ISSUE TITLE
Each Issue needs a cover image/thumbnail for its web page

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#405]

**Comment by srees95** [comment]
issue cover image can be the front cover
thumbnail can be a portion of/the whole front cover image with a large 1/2/3 etc on it, so that you can see what issue it is easily
e.g. very quick example thumbnail
![image1](https://user-images.githubusercontent.com/25647928/48224401-853e0f00-e391-11e8-92d8-098201804cd2.jpg)

**Comment by DeckOfPandas** [comment]
I mean image to use as the thumbnail -- sorry. Currently these cannot be different.

**Comment by DeckOfPandas** [comment]
Duplicate of #411 , closing
