### ISSUE TITLE
Canonical list of manuscript Types

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#428]
As discussed this morning, these will need to include posters that were submitted directly to us, plus posters we picked up from the conference. The Type will need to be changed internally for these as it stands.

We also have front matter for each Volume too, so in order for this to display in the ToC for the Volume it will need to be uploaded through the system at the Production stage of the workflow under appropriate Type.

Current list is:
![screen shot 2018-11-28 at 13 19 57](https://user-images.githubusercontent.com/2399432/49154485-612a7980-f310-11e8-954d-d9a9e78c803c.png)

This covers a few of the older Issues in this repo too, so I will track down and reference them as I go.

**Comment by DeckOfPandas** [comment]
See #370 for e.g.
"
-big agreement doc
-patient consent forms
"

**Comment by DeckOfPandas** [comment]
Current list on site is:
![27428393-c1ff07b8-5739-11e7-8ba8-0294a24453ed](https://user-images.githubusercontent.com/2399432/50287715-8ddb3800-045b-11e9-85c1-b4d94447e642.png)

Slack conversation just now:

![screen shot 2018-12-20 at 13 31 36](https://user-images.githubusercontent.com/2399432/50287738-a0ee0800-045b-11e9-948f-e17272898f87.png)

**Comment by DeckOfPandas** [comment]
We should also have "Journal Front Matter" for team page, Editorials and so on

**Comment by DeckOfPandas** [comment]
We already have some posters, so those need a section

**Comment by DeckOfPandas** [comment]
We already have conference abstracts, which need a section

**Comment by DeckOfPandas** [comment]
Lastly, we need to make sure that in the future we can publish on an ongoing basis, as per your "Bucket" thing in your diagram @srees95 

The best way to do this from a software POV is to make an issue with the right title etc, like 2019 Vol 1 or whatever, and to upload the raw submission and peer-review files as soon as they are accepted, just without assigning to some particular section. In this version of things, "publishing" the issue would mean picking a cutoff month, typsetting everything, assigning manuscripts to sections, and working out all page numbers, but the data already made public wouldn't need to change, just become citable.

In the field of academia SJWs this is called things like "Pre-publication publication" etc. Could also be "Raw".

What do you think?

In any case, called "Bucket" or not, this either needs to be a new section, or I need to substantially re-write the core OJS software......don't make me do that!

**Comment by srees95** [comment]
-original research
-QI/Audit
-Posters
-Conference
-Education
-Letters/opinions/reflections
-journal matter
-Supplementary (other)

**Comment by DeckOfPandas** [comment]
Totally agree with nice short list!

Things:
* What about "Journal front matter"?
* I'm not sure about the slashes -- what about , and

What should we call the "Pre-publication manuscripts"? <-- Oooh

What kind of things would go in Supplementary?

**Comment by srees95** [comment]
-Supplementary would literally just be things that people submit and they don't fit into any of the other categories because we've not thought of them e.g. if we run an essay competition, or artwork competition etc ect
--But they would probably email us and we can advise them to put it in one of the others or add one (can this be done after the first issue is out?)
-That was meant to say journal front matter

**Comment by srees95** [comment]
What About:
-Original Research
-QI/Audit
-Posters
-Conference
-Education
-Letters, Opinions, Reflections
-Journal front matter
-Competition
-Pre-publication Manuscripts

That covers everything (hopefully) and at least means the current submissions can be added, it can be altered in the next few days if anything major comes up that has been missed

**Comment by mhvbyrne** [comment]
Looks good! A couple of other ones would be useful:
Reviews - not technically original research and this will probably be our mainstay of what we recieve
Resource review - book reviews etc, might get one, you never know!
Images in medicine - so we have somewhere to put your surgeon picture

And for the current sections, could we make a couple of changes?
Quality improvement and audit
Competition - is currently competition entry

And we need to decided on capitalisation of each word is the first letter of every word going to be capitalised? I have no preference

**Comment by srees95** [comment]
The reason lit reviews weren't included is because we wont handle them differently from 'primary research' they won't be in a different section of the journal, so having a separate section wouldn't work.
I did consider resource reviews, but didn't include it because I think it's very unlikely to be submitted, we have nothing in place for wether they get peer reviewed or not (and if not they can just be included in education/editorials).
And Images in medicine comes under competition entries I recon, we're not going to get anyone submitting pictures without an invitation, and when we tell people they can it would be part of a competition.

**Comment by srees95** [comment]
I've made the change to QI/Audit,
why the change from competition entry to competition?
I've capitalised them as if titles, because they're titles of sections, and that's how they'll appear on the site

**Comment by mhvbyrne** [comment]
I agree we don't handle them differently to primary research, but we can't put reviews in a category called original research because that's misleading. If you want to group them together they'll need a broader name, but I'd rather keep them separate as it's not so much how we handle them, but these sections are the titles that display in the published issue.
I still think images in medicine should be a thing on its own, someone might take a cool picture on their elective or something similar to your art piece might be submitted, which we haven't put out a competition request for.

**Comment by mhvbyrne** [comment]
Case reports also missing
