### ISSUE TITLE
Spec for URLs for Volumes and Manuscripts

### ISSUE THREAD

**Issue by DeckOfPandas** [NSAMR/uk.ac.nsamr.journal#431]
Set in metadata for each manuscript during submission process

This needs to be done once and properly so we don't break people's bookmarks or change URLs that people might cite

Literally cannot change at all for any reason after pressing "publish"

**Comment by mhvbyrne** [comment]
We could use the number that is associated with each article in OJS, that is openly accessible to all and is standardised

**Comment by mhvbyrne** [comment]
Could we use the number that is associated with each article in OJS?

**Comment by DeckOfPandas** [comment]
No need Matt -- that number is only ever used internally

The metadata I mean is:
* https://journal.nsamr.ac.uk/index.php/jsamr/issue/view/ISSUE_SLUG e.g. .../2018-1
* https://journal.nsamr.ac.uk/index.php/jsamr/article/view/ARTICLE_SLUG e.g. .../2018-1-jackson

These are entered via the submissions process screens

**Comment by mhvbyrne** [comment]
We have now changed to volume, issue
Galley spec will be: 2018-1-1-jackson
2018 - year
1 - volume
1 - issue
jackson - author

For multiple publications by the same first author in the same issue it will be: 2018-1-1-jackson-2
Where the last number, in this example 2, signifies the second publication by that author in that issue. The first manuscript published in that issue is NOT numbered

ALTERNATIVELY

We could just use the number that is associated with each article in OJS

e.g. jackson may be numbered 55 in the OJS software

Therefore it could be: 2018-1-1-55
